export const itemArr = [
    {
        collection: 'Back To School',
        color: 'pink',
        year: 2006,
        metal: 'pink gold',
        quantity: 3,
        price: 160,
        ispopular: true,
        img: './assets/image/img/earrings1.jpg',
        id: 1,
    },
    {
        collection: 'Back To School',
        color: 'pink',
        year: 2005,
        metal: 'pink gold',
        quantity: 9,
        price: 130,
        ispopular: true,
        img: './assets/image/img/earrings6.jpg',
        id: 6,
    },
    {
        collection: 'Back To School',
        color: 'grey',
        year: 2000,
        metal: 'silver',
        quantity: 15,
        price: 85,
        ispopular: true,
        img: './assets/image/img/earrings9.jpg',
        id: 9,
    },
    {
        collection: 'Milan',
        color: 'pink',
        year: 2022,
        metal: 'pink gold',
        quantity: 1,
        price: 210,
        ispopular: false,
        img: './assets/image/img/earrings3.jpg',
        id: 3,
    },
    {
        collection: 'Milan',
        color: 'yellow',
        year: 2014,
        metal: 'gold',
        quantity: 6,
        price: 155,
        ispopular: false,
        img: './assets/image/img/earrings7.jpg',
        id: 7,
    },
    {
        collection: 'Portugal',
        color: 'yellow',
        year: 2018,
        metal: 'gold',
        quantity: 4,
        price: 185,
        ispopular: false,
        img: './assets/image/img/earrings4.jpg',
        id: 4,
    },
    {
        collection: 'Portugal',
        color: 'yellow',
        year: 2020,
        metal: 'gold',
        quantity: 4,
        price: 185,
        ispopular: true,
        img: './assets/image/img/earrings5.jpg',
        id: 5,
    },
    {
        collection: 'Portugal',
        color: 'yellow',
        year: 2004,
        metal: 'gold',
        quantity: 1,
        price: 105,
        ispopular: false,
        img: './assets/image/img/earrings8.jpg',
        id: 8,
    },
    {
        collection: 'Portugal',
        color: 'yellow',
        year: 2019,
        metal: 'gold',
        quantity: 9,
        price: 260,
        ispopular: true,
        img: './assets/image/img/earrings12.jpg',
        id: 12,
    },
    {
        collection: 'Timeless Elegance',
        color: 'yellow',
        year: 2010,
        metal: 'gold',
        quantity: 8,
        price: 120,
        ispopular: false,
        img: './assets/image/img/earrings2.jpg',
        id: 2,
    },
    {
        collection: 'Timeless Elegance',
        color: 'yellow',
        year: 2017,
        metal: 'gold',
        quantity: 6,
        price: 125,
        ispopular: false,
        img: './assets/image/img/earrings10.jpg',
        id: 10,
    },
    {
        collection: 'Timeless Elegance',
        color: 'pink',
        year: 2021,
        metal: 'pink gold',
        quantity: 7,
        price: 200,
        ispopular: false,
        img: './assets/image/img/earrings11.jpg',
        id: 11,
    },
];
